import React, { createContext, useContext, useEffect, useState } from 'react';

const translations = {
  vn: {
    dashboard: 'Tong quan',
    remote_control: 'Dieu khien',
    fingerprints: 'Van tay',
    logs: 'Nhat ky',
    analytics: 'Phan tich',
    settings: 'Cai dat',
    support: 'Ho tro',
    support_page: 'Trang ho tro',
    voice_control: 'Dieu khien giong noi',
    voice_ready: 'San sang',
    voice_listening: 'Dang nghe',
    voice_processing: 'Dang xu ly',
    voice_close: 'Dong voice panel',
    voice_transcript: 'Noi dung nghe duoc',
    voice_speak_now: 'Hay noi lenh cua ban.',
    voice_no_transcript: 'Chua co lenh nao.',
    voice_examples: 'Lenh mau',
    voice_history: 'Lich su lenh',
    voice_panel: 'Voice',
    voice_start: 'Bat dau nghe',
    voice_stop: 'Dung nghe',
    voice_shortcut: 'Ctrl + Shift + V',
    voice_verify: 'Xac thuc',
    voice_cancel: 'Huy',
    logout: 'Dang xuat',
    admin: 'Admin',
    admin_sub: 'Quan tri vien',
    search: 'Tim kiem thiet bi...',
    sys_status: 'Trang thai he thong',
    locked: 'DA KHOA',
    unlocked: 'DA MO',
    sys_desc: 'He thong an ninh Sentinel dang hoat dong. Tat ca diem truy cap deu duoc bao mat.',
    wifi: 'Tin hieu wifi',
    battery: 'Dung luong pin',
    environment: 'Moi truong hien tai',
    weather: 'Thoi tiet',
    brightness: 'Do sang (LDR)',
    indoor: 'Trong nha',
    gas: 'Nong do gas',
    safe: 'An toan',
    sensor_detail: 'Xem chi tiet cam bien',
    alerts: 'Canh bao gan day',
    view_all: 'Xem tat ca',
    live: 'TRUC TIEP',
    front_door: 'Cua chinh',
    last_update: 'Cap nhat lan cuoi',
    playback: 'Xem lai',
    talk: 'Dam thoai',
    loading: 'Dang tai...',
    current_device: 'Thiet bi hien tai',
    current_device_fallback: 'Chua chon thiet bi',
    online: 'Online',
    offline: 'Offline',
    system_time: 'Thoi gian he thong',
    switch_language: 'Chuyen ngon ngu',
    switch_theme: 'Chuyen giao dien',
    sentinel_user: 'Nguoi dung Sentinel',
    page_overview_title: 'Tong quan he thong',
    page_overview_subtitle: 'Trang thai cua, canh bao va du lieu can xu ly ngay.',
    page_remote_title: 'Dieu khien thiet bi',
    page_remote_subtitle: 'Gui lenh khoa mo va cap nhat cai dat an toan.',
    page_fingerprints_title: 'Quan ly van tay',
    page_fingerprints_subtitle: 'Kiem tra danh sach van tay dang duoc cap quyen.',
    page_logs_title: 'Nhat ky su kien',
    page_logs_subtitle: 'Theo doi lich su truy cap, canh bao va thao tac he thong.',
    page_analytics_title: 'Phan tich hoat dong',
    page_analytics_subtitle: 'Tong hop xu huong va muc do on dinh cua thiet bi.',
    page_settings_title: 'Tai khoan va tuy chon',
    page_settings_subtitle: 'Cap nhat thong tin nguoi dung, thong bao va bao mat.',
    profile_view: 'Xem ho so',
    profile_view_desc: 'Xem thong tin tai khoan hien tai',
    profile_edit: 'Sua ho so',
    profile_edit_desc: 'Cap nhat avatar va thong tin ca nhan',
    preferences: 'Tuy chon',
    preferences_desc: 'Giao dien va cai dat tai khoan',
    login_activity: 'Hoat dong dang nhap',
    login_activity_desc: 'Phien dang nhap va thiet bi gan day',
    signing_out: 'Dang dang xuat...',
    hero_attention: 'Can xu ly ngay',
    hero_stable: 'He thong on dinh',
    hero_needs_review: 'He thong dang phat hien su kien can kiem tra.',
    hero_device_online: 'dang ket noi binh thuong.',
    hero_no_device_online: 'Chua co thiet bi online. Kiem tra ket noi truoc khi dieu khien.',
    hero_scan: 'Tong quan 3 giay',
    door_status: 'Trang thai cua',
    active_alerts: 'Canh bao kich hoat',
    device_label: 'Thiet bi',
    door_locked_now: 'Da khoa',
    door_unlocked_now: 'Dang mo',
    unlock_now: 'Mo khoa ngay',
    lock_now: 'Khoa cua ngay',
    view_alert_details: 'Xem canh bao chi tiet',
    view_weekly_report: 'Xem bao cao tuan',
    next_action: 'Hanh dong tiep theo',
    system_locked: 'He thong dang khoa',
    relock_needed: 'Can khoa lai cua',
    next_action_online: 'Chuyen sang trang Dieu khien de xac thuc va gui lenh khoa/mo.',
    next_action_offline: 'Thiet bi dang offline. Kiem tra ket noi truoc khi thao tac.',
    last_seen: 'Lan cap nhat cuoi',
    latest_command: 'Lenh gan nhat',
    ready: 'San sang',
    active_alerts_title: 'Canh bao dang hoat dong',
    active_alerts_count_suffix: 'canh bao can kiem tra',
    no_active_alerts: 'Khong co canh bao dang kich hoat',
    view_logs: 'Xem nhat ky',
    loading_alerts: 'Dang tai canh bao...',
    system_safe: 'He thong an toan',
    system_safe_desc: 'Khong co canh bao nao can xu ly o thoi diem hien tai.',
    event_recent: 'Su kien gan day',
    event_recent_desc: 'Tra loi nhanh: cua da khoa chua, ai vua thao tac, co su co nao moi khong.',
    view_all_full: 'Xem toan bo',
    loading_events: 'Dang tai su kien...',
    no_events: 'Chua co su kien nao trong nhat ky.',
    system_actor: 'He thong',
    environment_desc: 'Gia tri hien tai, don vi va muc canh bao co ban.',
    view_device: 'Xem thiet bi',
    weather_support: 'Du lieu bo tro hien tai',
    ldr_sensor: 'Cam bien LDR',
    no_sensor_data: 'Chua co du lieu tu cam bien',
    threshold_label: 'Nguong canh bao',
    too_bright: 'Qua sang',
    stable: 'On dinh',
    current_threshold: 'Nguong hien tai',
    needs_attention: 'Can chu y',
    motion_detected: 'Dang phat hien chuyen dong',
    no_intrusion: 'Khong co xam nhap',
    weekly_report: 'Bao cao tuan',
    weekly_report_loading: 'Dang tong hop xu huong 7 ngay qua.',
    weekly_report_fallback: 'Tong hop nhanh de xem he thong co on dinh hay khong.',
    view_analytics: 'Xem phan tich',
    total_access: 'Luot truy cap',
    new_alerts: 'Canh bao moi',
    critical_level: 'Muc nguy cap',
    no_major_change: 'Khong co thay doi lon',
    review_logs: 'Can xem lai nhat ky va xu ly',
    no_new_alerts: 'Khong co canh bao moi',
    prioritize_now: 'Can uu tien xu ly',
    system_stable: 'He thong van on dinh',
    quick_insight: 'Insight nhanh',
    insight_critical: 'Tuan nay co canh bao nguy cap. Uu tien vao trang Nhat ky de kiem tra nguyen nhan va thoi diem xay ra.',
    insight_warning: 'Co canh bao moi trong tuan nhung chua o muc nguy cap. Nen xem lai nhat ky de dam bao da xu ly day du.',
    insight_ok: 'He thong van on dinh trong 7 ngay qua. Tiep tuc theo doi ket noi thiet bi va log truy cap.',
    device_image: 'Hinh anh thiet bi',
    device_preview: 'Preview thiet bi',
    device_preview_desc: 'Day la khung preview thiet bi, khong phai live camera. Neu can goc nhin truc tiep, nen tach thanh module camera rieng voi trang thai ket noi ro rang.',
    control_device: 'Dieu khien thiet bi',
    open_logs: 'Mo nhat ky',
    nav_scope_overview: 'Trang thai tong the cua he thong',
    nav_scope_remote: 'Thao tac khoa mo va cai dat thiet bi',
    nav_scope_fingerprints: 'Quan ly danh tinh va van tay',
    nav_scope_logs: 'Theo doi lich su va su kien',
    nav_scope_analytics: 'Bao cao va xu huong',
    nav_scope_settings: 'Tai khoan, bao mat va thong bao',
    viewing: 'Dang xem',
    open_sidebar: 'Mo rong thanh dieu huong',
    collapse_sidebar: 'Thu gon thanh dieu huong',
    open_sidebar_short: 'Mo rong sidebar',
    collapse_sidebar_short: 'Thu gon sidebar',
    alert_critical: 'Nguy cap',
    alert_high: 'Can chu y',
    alert_track: 'Theo doi',
    alert_gas_leak: 'Canh bao khi gas',
    alert_intruder: 'Canh bao dot nhap',
    alert_fire: 'Canh bao chay',
    alert_wrong_password: 'Sai mat khau',
    alert_tamper: 'Canh bao pha hoai',
    alert_battery_low: 'Pin yeu',
    alert_offline: 'Thiet bi offline',
    no_data: 'Chua co du lieu',
    not_updated: 'Chua cap nhat',
    minutes_ago: 'phut truoc',
    hours_ago: 'gio truoc',
    days_ago: 'ngay truoc',
    fingerprints_total: 'Tong so van tay',
    fingerprints_active_today: 'Hoat dong trong ngay',
    fingerprints_security_level: 'Muc do bao mat',
    fingerprints_security_high: 'Cao',
    fingerprints_security_standard: 'Chuan',
    fingerprints_registry_title: 'Danh sach dang ky',
    fingerprints_registry_desc: 'Quan ly va giam sat quyen truy cap sinh trac hoc theo thoi gian thuc.',
    fingerprints_add_new: 'Them van tay moi',
    fingerprints_table_slot: 'Slot ID',
    fingerprints_table_user: 'Ten nguoi dung',
    fingerprints_table_access: 'Cap do truy cap',
    fingerprints_table_metadata: 'Metadata dang ky',
    fingerprints_table_last_active: 'Hoat dong lan cuoi',
    fingerprints_table_actions: 'Thao tac',
    fingerprints_empty: 'Chua co van tay nao duoc dang ky.',
    fingerprints_status_normal: 'Binh thuong',
    fingerprints_status_disabled: 'Vo hieu hoa',
    fingerprints_slot_label: 'Slot',
    fingerprints_active: 'Active',
    fingerprints_inactive: 'Inactive',
    fingerprints_pagination_summary: 'Hien thi 4 trong so 128 ket qua',
    fingerprints_system_status: 'Trang thai he thong',
    fingerprints_system_status_desc: 'Tat ca cam bien van tay dang hoat dong binh thuong. Ma hoa dau cuoi da duoc kich hoat.',
    fingerprints_load_error: 'Khong the ket noi den may chu.',
    fingerprints_level_standard: 'Standard',
    fingerprints_level_admin: 'Admin',
    fingerprints_level_guest: 'Guest',
    fingerprints_enrollment_label: 'Dang ky van tay',
    fingerprints_add_modal_title: 'Them van tay moi',
    fingerprints_add_modal_desc: 'Giao dien nay mo phong quy trinh them van tay o frontend. Khi backend san sang, phan submit co the noi truc tiep vao API enrollment ma khong can doi layout.',
    fingerprints_close_modal: 'Dong hop thoai them van tay',
    fingerprints_form_name: 'Ten nguoi dung',
    fingerprints_form_name_placeholder: 'Nhap ten nguoi dang ky',
    fingerprints_form_access: 'Cap do truy cap',
    fingerprints_form_slot: 'Slot dang ky',
    fingerprints_form_slot_placeholder: 'Vi du: 12',
    fingerprints_form_note: 'Ghi chu noi bo',
    fingerprints_form_note_placeholder: 'Mo ta them ve nguoi dung, ngon tay dang ky, hoac ghi chu van hanh.',
    fingerprints_sensor_status: 'Trang thai cam bien',
    fingerprints_sensor_ready: 'San sang enrollment',
    fingerprints_sensor_ready_desc: 'Thiet bi dang online va co the bat dau nhan van tay moi.',
    fingerprints_process_title: 'Quy trinh de xuat',
    fingerprints_process_desc: '1. Xac nhan thong tin nguoi dung. 2. Chon slot va khoi dong enrollment. 3. Yeu cau dat ngon tay 2-3 lan. 4. Luu ket qua dang ky khi thiet bi tra ve thanh cong.',
    fingerprints_close: 'Dong',
    fingerprints_start_enrollment: 'Bat dau dang ky',
    fingerprints_preview: 'Preview',
    fingerprints_new_user: 'Nguoi dung moi',
    fingerprints_expected_slot: 'Slot du kien',
    fingerprints_not_selected: 'Chua chon',
    fingerprints_progress: 'Tien trinh',
    fingerprints_progress_desc: 'Buoc 1/3: Nhap thong tin va san sang ket noi voi thiet bi.',
    fingerprints_note_title: 'Luu y thao tac',
    fingerprints_note_desc: 'Nguoi dung nen dat ngon tay sach, kho va dung vi tri trong moi lan quet de tang do chinh xac.',
    reminder_warning: 'Cảnh báo',
    reminder_error: 'Lỗi hệ thống',
    reminder_info: 'Thông tin',
    reminder_success: 'Thành công',
    reminder_check_now: 'Kiểm tra ngay',
    reminder_close: 'Đóng',
    reminder_session_expired: 'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.',
    reminder_device_offline: 'Không thể kết nối tới thiết bị. Kiểm tra nguồn điện và mạng.',
    reminder_unsaved_changes: 'Bạn có thay đổi chưa lưu. Rời khỏi trang sẽ mất dữ liệu.',
    reminder_gas_detected: 'Hệ thống phát hiện nồng độ gas cao. Kiểm tra ngay!',
    reminder_intruder_detected: 'Phát hiện truy cập trái phép. Kiểm tra camera và nhật ký.',
  },
  en: {
    dashboard: 'Overview',
    remote_control: 'Control',
    fingerprints: 'Fingerprints',
    logs: 'Logs',
    analytics: 'Analytics',
    settings: 'Settings',
    support: 'Support',
    support_page: 'Support Page',
    voice_control: 'Voice control',
    voice_ready: 'Ready',
    voice_listening: 'Listening',
    voice_processing: 'Processing',
    voice_close: 'Close voice panel',
    voice_transcript: 'Live transcript',
    voice_speak_now: 'Speak a command now.',
    voice_no_transcript: 'No voice command captured yet.',
    voice_examples: 'Sample phrases',
    voice_history: 'Command history',
    voice_panel: 'Voice',
    voice_start: 'Start listening',
    voice_stop: 'Stop listening',
    voice_shortcut: 'Ctrl + Shift + V',
    voice_verify: 'Verify',
    voice_cancel: 'Cancel',
    logout: 'Log out',
    admin: 'Admin',
    admin_sub: 'Administrator',
    search: 'Search devices...',
    sys_status: 'System status',
    locked: 'LOCKED',
    unlocked: 'UNLOCKED',
    sys_desc: 'Sentinel security system is active. All access points are secured.',
    wifi: 'Wi-Fi signal',
    battery: 'Battery level',
    environment: 'Current environment',
    weather: 'Weather',
    brightness: 'Brightness (LDR)',
    indoor: 'Indoor',
    gas: 'Gas level',
    safe: 'Safe',
    sensor_detail: 'View sensor details',
    alerts: 'Recent alerts',
    view_all: 'View all',
    live: 'LIVE',
    front_door: 'Front door',
    last_update: 'Last updated',
    playback: 'Playback',
    talk: 'Talk',
    loading: 'Loading...',
    current_device: 'Current device',
    current_device_fallback: 'No device selected',
    online: 'Online',
    offline: 'Offline',
    system_time: 'System time',
    switch_language: 'Switch language',
    switch_theme: 'Switch theme',
    sentinel_user: 'Sentinel User',
    page_overview_title: 'System overview',
    page_overview_subtitle: 'Door status, active alerts, and data that needs action now.',
    page_remote_title: 'Device control',
    page_remote_subtitle: 'Send lock commands and update safety settings.',
    page_fingerprints_title: 'Fingerprint management',
    page_fingerprints_subtitle: 'Review fingerprints that currently have access.',
    page_logs_title: 'Event log',
    page_logs_subtitle: 'Track access history, alerts, and system actions.',
    page_analytics_title: 'Activity analytics',
    page_analytics_subtitle: 'Review trends and overall device stability.',
    page_settings_title: 'Account and preferences',
    page_settings_subtitle: 'Update profile, notifications, and security options.',
    profile_view: 'View profile',
    profile_view_desc: 'Review your current account details',
    profile_edit: 'Edit profile',
    profile_edit_desc: 'Update avatar and personal information',
    preferences: 'Settings',
    preferences_desc: 'Appearance and account preferences',
    login_activity: 'Login activity',
    login_activity_desc: 'Recent sessions and devices',
    signing_out: 'Signing out...',
    hero_attention: 'Needs attention now',
    hero_stable: 'System stable',
    hero_needs_review: 'The system has detected an event that should be reviewed.',
    hero_device_online: 'is connected and operating normally.',
    hero_no_device_online: 'No online devices found. Check connectivity before sending commands.',
    hero_scan: 'Three-second summary',
    door_status: 'Door status',
    active_alerts: 'Active alerts',
    device_label: 'Device',
    door_locked_now: 'Locked',
    door_unlocked_now: 'Unlocked',
    unlock_now: 'Unlock now',
    lock_now: 'Lock now',
    view_alert_details: 'View alert details',
    view_weekly_report: 'View weekly report',
    next_action: 'Next action',
    system_locked: 'System is locked',
    relock_needed: 'Door should be locked again',
    next_action_online: 'Go to the Control page to verify identity and send a lock or unlock command.',
    next_action_offline: 'The device is offline. Check connectivity before taking action.',
    last_seen: 'Last seen',
    latest_command: 'Latest command',
    ready: 'Ready',
    active_alerts_title: 'Active alerts',
    active_alerts_count_suffix: 'alerts need review',
    no_active_alerts: 'No active alerts',
    view_logs: 'View logs',
    loading_alerts: 'Loading alerts...',
    system_safe: 'System secure',
    system_safe_desc: 'There are no alerts that require action right now.',
    event_recent: 'Recent events',
    event_recent_desc: 'Answer quickly: is the door locked, who acted last, and is there any new issue?',
    view_all_full: 'View all',
    loading_events: 'Loading events...',
    no_events: 'No events in the log yet.',
    system_actor: 'System',
    environment_desc: 'Current values, units, and basic warning thresholds.',
    view_device: 'View device',
    weather_support: 'Current supporting data',
    ldr_sensor: 'LDR sensor',
    no_sensor_data: 'No sensor data available',
    threshold_label: 'Warning threshold',
    too_bright: 'Too bright',
    stable: 'Stable',
    current_threshold: 'Current threshold',
    needs_attention: 'Needs attention',
    motion_detected: 'Motion currently detected',
    no_intrusion: 'No intrusion detected',
    weekly_report: 'Weekly report',
    weekly_report_loading: 'Compiling the last 7 days of activity...',
    weekly_report_fallback: 'A quick summary to check whether the system stayed stable.',
    view_analytics: 'View analytics',
    total_access: 'Access count',
    new_alerts: 'New alerts',
    critical_level: 'Critical level',
    no_major_change: 'No major change',
    review_logs: 'Review logs and resolve if needed',
    no_new_alerts: 'No new alerts',
    prioritize_now: 'Prioritize now',
    system_stable: 'System remained stable',
    quick_insight: 'Quick insight',
    insight_critical: 'There were critical alerts this week. Go to Logs first to review cause and timing.',
    insight_warning: 'There were new alerts this week, but not at a critical level. Review the log to confirm everything was handled.',
    insight_ok: 'The system stayed stable over the last 7 days. Keep monitoring device connectivity and access activity.',
    device_image: 'Device image',
    device_preview: 'Device preview',
    device_preview_desc: 'This is a device preview, not a live camera feed. If you need live video, it should be a dedicated module with clear connection state.',
    control_device: 'Control device',
    open_logs: 'Open logs',
    nav_scope_overview: 'Overall system state',
    nav_scope_remote: 'Lock, unlock, and configure device settings',
    nav_scope_fingerprints: 'Identity and fingerprint management',
    nav_scope_logs: 'History and event tracking',
    nav_scope_analytics: 'Reports and trends',
    nav_scope_settings: 'Account, security, and notification settings',
    viewing: 'Viewing',
    open_sidebar: 'Expand navigation',
    collapse_sidebar: 'Collapse navigation',
    open_sidebar_short: 'Expand sidebar',
    collapse_sidebar_short: 'Collapse sidebar',
    alert_critical: 'Critical',
    alert_high: 'Needs review',
    alert_track: 'Tracking',
    alert_gas_leak: 'Gas leak alert',
    alert_intruder: 'Intruder alert',
    alert_fire: 'Fire alarm',
    alert_wrong_password: 'Wrong password',
    alert_tamper: 'Tamper alert',
    alert_battery_low: 'Low battery',
    alert_offline: 'Device offline',
    no_data: 'No data available',
    not_updated: 'Not updated yet',
    minutes_ago: 'minutes ago',
    hours_ago: 'hours ago',
    days_ago: 'days ago',
    fingerprints_total: 'Total fingerprints',
    fingerprints_active_today: 'Activity today',
    fingerprints_security_level: 'Security level',
    fingerprints_security_high: 'High',
    fingerprints_security_standard: 'Standard',
    fingerprints_registry_title: 'Enrollment list',
    fingerprints_registry_desc: 'Manage and monitor biometric access permissions in real time.',
    fingerprints_add_new: 'Add new fingerprint',
    fingerprints_table_slot: 'Slot ID',
    fingerprints_table_user: 'User name',
    fingerprints_table_access: 'Access level',
    fingerprints_table_metadata: 'Enrollment metadata',
    fingerprints_table_last_active: 'Last activity',
    fingerprints_table_actions: 'Actions',
    fingerprints_empty: 'No fingerprints have been registered yet.',
    fingerprints_status_normal: 'Normal',
    fingerprints_status_disabled: 'Disabled',
    fingerprints_slot_label: 'Slot',
    fingerprints_active: 'Active',
    fingerprints_inactive: 'Inactive',
    fingerprints_pagination_summary: 'Showing 4 of 128 results',
    fingerprints_system_status: 'System status',
    fingerprints_system_status_desc: 'All fingerprint sensors are operating normally. End-to-end encryption is active.',
    fingerprints_load_error: 'Unable to connect to the server.',
    fingerprints_level_standard: 'Standard',
    fingerprints_level_admin: 'Admin',
    fingerprints_level_guest: 'Guest',
    fingerprints_enrollment_label: 'Fingerprint enrollment',
    fingerprints_add_modal_title: 'Add new fingerprint',
    fingerprints_add_modal_desc: 'This frontend flow simulates fingerprint enrollment. When the backend is ready, submission can connect directly to the enrollment API without changing the layout.',
    fingerprints_close_modal: 'Close add fingerprint dialog',
    fingerprints_form_name: 'User name',
    fingerprints_form_name_placeholder: 'Enter the enrollee name',
    fingerprints_form_access: 'Access level',
    fingerprints_form_slot: 'Enrollment slot',
    fingerprints_form_slot_placeholder: 'Example: 12',
    fingerprints_form_note: 'Internal note',
    fingerprints_form_note_placeholder: 'Describe the user, selected finger, or any operational note.',
    fingerprints_sensor_status: 'Sensor status',
    fingerprints_sensor_ready: 'Ready for enrollment',
    fingerprints_sensor_ready_desc: 'The device is online and ready to capture a new fingerprint.',
    fingerprints_process_title: 'Recommended flow',
    fingerprints_process_desc: '1. Confirm user information. 2. Pick a slot and start enrollment. 3. Ask the user to place the finger 2 to 3 times. 4. Save the result when the device reports success.',
    fingerprints_close: 'Close',
    fingerprints_start_enrollment: 'Start enrollment',
    fingerprints_preview: 'Preview',
    fingerprints_new_user: 'New user',
    fingerprints_expected_slot: 'Expected slot',
    fingerprints_not_selected: 'Not selected',
    fingerprints_progress: 'Progress',
    fingerprints_progress_desc: 'Step 1/3: Enter details and prepare device connection.',
    fingerprints_note_title: 'Handling note',
    fingerprints_note_desc: 'The user should keep the finger clean, dry, and aligned consistently during each scan for better accuracy.',
    reminder_warning: 'Warning',
    reminder_error: 'System Error',
    reminder_info: 'Information',
    reminder_success: 'Success',
    reminder_check_now: 'Check Now',
    reminder_close: 'Close',
    reminder_session_expired: 'Session has expired. Please log in again.',
    reminder_device_offline: 'Unable to connect to the device. Check power and network.',
    reminder_unsaved_changes: 'You have unsaved changes. Leaving will lose data.',
    reminder_gas_detected: 'High gas concentration detected. Check immediately!',
    reminder_intruder_detected: 'Unauthorized access detected. Check camera and logs.',
  },
};

const phraseTranslations = {
  vn: {
    app_brand_full: 'Hệ thống an toàn nhà thông minh',
    notifications: 'Thông báo',
    open_notifications: 'Mở thông báo',
    recent_notifications: 'Thông báo gần đây',
    unresolved_alerts: 'cảnh báo chưa xử lý',
    no_new_notifications: 'Không có thông báo mới',
    system_notification: 'Thông báo hệ thống',
    just_now: 'Vừa xong',
    all_devices: 'Tất cả thiết bị',
    device_offline_short: 'Thiết bị mất kết nối',
    system_online_short: 'Hệ thống đang hoạt động',
    unavailable: 'Chưa có dữ liệu',
    current_browser_session: 'Trình duyệt đang dùng',
    unknown_device: 'Thiết bị không xác định',
    unknown_info: 'Chưa có thông tin',
    action_success: 'Thành công',
    action_denied: 'Từ chối',
    action_warning: 'Cảnh báo',
    access_event: 'Ra vào',
    warning_event: 'Cảnh báo',
    command_event: 'Lệnh điều khiển',
    locked_action: 'Đã khóa',
    unlocked_action: 'Đã mở',
    remote_method: 'Điều khiển từ xa',
    fingerprint_method: 'Vân tay',
    voice_method: 'Giọng nói',
    keypad_method: 'Mã số',
    system_method: 'Hệ thống',
    auto_lock: 'Tự khóa cửa',
    gas_alert: 'Cảnh báo khí gas',
    motion_alert: 'Cảnh báo chuyển động',
    gas_threshold: 'Mức khí gas cảnh báo (ppm)',
    light_threshold: 'Mức ánh sáng cảnh báo (lux)',
    auto_lock_delay: 'Thời gian tự khóa (giây)',
    save_command: 'Lưu lệnh',
    custom_commands: 'Lệnh giọng nói tự tạo',
    custom_commands_desc: 'Gắn câu nói của bạn với một thao tác trong hệ thống.',
    how_it_works: 'Cách hoạt động',
    account_settings_title: 'Cài đặt tài khoản',
    account_settings_desc: 'Quản lý ảnh đại diện, hồ sơ, thông báo và phiên đăng nhập.',
    users_title: 'Quản lý người dùng',
    users_desc: 'Quản lý người dùng và các phiên đăng nhập trong hệ thống.',
    analytics_sensor_report: 'Báo cáo cảm biến',
    analytics_sensor_title: 'Theo dõi cảm biến',
    analytics_sensor_desc: 'Xem nhiệt độ, độ ẩm, khí gas, ánh sáng, chuyển động và trạng thái cửa theo từng khoảng thời gian.',
    overview_chart: 'Biểu đồ tổng quan',
    sensor_values_over_time: 'Các chỉ số cảm biến theo thời gian',
    common_values: 'Giá trị thường gặp',
    sensor_average_title: 'Mức trung bình của từng cảm biến',
    view_each_sensor: 'Xem từng cảm biến',
    sensor_summary: 'Tóm tắt cảm biến',
    sensor_history: 'Lịch sử cảm biến',
    device_sensor_status: 'Tình trạng cảm biến của từng khóa',
    average: 'Trung bình',
    highest: 'Cao nhất',
    current: 'Hiện tại',
    total_times: 'Tổng số lần',
    logs_title: 'Nhật ký ra vào',
    logs_desc: 'Theo dõi mọi lần mở cửa, cảnh báo và lệnh điều khiển theo thời gian thực.',
    export_csv: 'Xuất báo cáo CSV',
    choose_device: 'Chọn thiết bị',
    time_range: 'Khoảng thời gian',
    event_type: 'Loại sự kiện',
    all_time: 'Mọi lúc',
    today: 'Hôm nay',
    last_7_days: '7 ngày qua',
    this_month: 'Tháng này',
    all: 'Tất cả',
    time: 'Thời gian',
    actor: 'Người dùng / thiết bị',
    action_detail: 'Chi tiết thao tác',
    try_again: 'Thử lại',
    no_matching_logs: 'Không tìm thấy bản ghi nào khớp với bộ lọc.',
    showing_filtered_results: 'Hiển thị tất cả kết quả khớp với bộ lọc.',
    login_title: 'Đăng nhập',
    login_desc: 'Nhập tài khoản để điều khiển thiết bị an toàn.',
    login_submit: 'Kết nối an toàn',
    register_title: 'Đăng ký',
    register_desc: 'Tạo tài khoản để sử dụng hệ thống.',
    register_submit: 'Tạo tài khoản',
    remember_session: 'Duy trì phiên đăng nhập',
    forgot_password: 'Quên mật khẩu?',
    no_account: 'Chưa có tài khoản?',
    have_account: 'Đã có tài khoản?',
    sensor_temperature: 'Nhiệt độ',
    sensor_humidity: 'Độ ẩm',
    sensor_gas: 'Khí gas',
    sensor_light: 'Độ sáng',
    sensor_motion: 'Chuyển động',
    sensor_door_open: 'Cửa mở',
    sensor_door_close: 'Cửa đóng',
    users: 'Người dùng',
    global_sessions: 'Phiên đăng nhập',
    full_name: 'Họ và tên',
    role: 'Vai trò',
    status: 'Trạng thái',
    last_login: 'Đăng nhập gần nhất',
    actions: 'Thao tác',
    enable: 'Bật',
    disable: 'Tắt',
    active: 'Đang hoạt động',
    disabled: 'Đã tắt',
    signed_in: 'Đã đăng nhập',
    last_active: 'Hoạt động gần nhất',
    logged_out: 'Đã đăng xuất',
  },
  en: {
    app_brand_full: 'Integrated Home Safety',
    notifications: 'Notifications',
    open_notifications: 'Open notifications',
    recent_notifications: 'Recent notifications',
    unresolved_alerts: 'unresolved alerts',
    no_new_notifications: 'No new notifications',
    system_notification: 'System notification',
    just_now: 'Just now',
    all_devices: 'All devices',
    device_offline_short: 'Device offline',
    system_online_short: 'System online',
    unavailable: 'Unavailable',
    current_browser_session: 'Current browser session',
    unknown_device: 'Unknown device',
    unknown_info: 'Unknown',
    action_success: 'Successful',
    action_denied: 'Denied',
    action_warning: 'Warning',
    access_event: 'Access',
    warning_event: 'Warning',
    command_event: 'Command',
    locked_action: 'Locked',
    unlocked_action: 'Unlocked',
    remote_method: 'Remote',
    fingerprint_method: 'Fingerprint',
    voice_method: 'Voice',
    keypad_method: 'Keypad',
    system_method: 'System',
    auto_lock: 'Auto lock',
    gas_alert: 'Gas alert',
    motion_alert: 'Motion alert',
    gas_threshold: 'Gas warning level (ppm)',
    light_threshold: 'Light warning level (lux)',
    auto_lock_delay: 'Auto-lock delay (seconds)',
    save_command: 'Save command',
    custom_commands: 'Custom voice commands',
    custom_commands_desc: 'Map your own spoken phrase to a system action.',
    how_it_works: 'How it works',
    account_settings_title: 'Account settings',
    account_settings_desc: 'Manage avatar, profile details, alerts, and login sessions.',
    users_title: 'User management',
    users_desc: 'Manage system users and active login sessions.',
    analytics_sensor_report: 'Sensor report',
    analytics_sensor_title: 'Sensor monitoring',
    analytics_sensor_desc: 'View temperature, humidity, gas, light, motion, and door status by time range.',
    overview_chart: 'Overview chart',
    sensor_values_over_time: 'Sensor values over time',
    common_values: 'Common values',
    sensor_average_title: 'Average level for each sensor',
    view_each_sensor: 'View each sensor',
    sensor_summary: 'Sensor summary',
    sensor_history: 'Sensor history',
    device_sensor_status: 'Sensor status by lock',
    average: 'Average',
    highest: 'Highest',
    current: 'Current',
    total_times: 'Total times',
    logs_title: 'Access log',
    logs_desc: 'Track door activity, alerts, and control commands in real time.',
    export_csv: 'Export CSV report',
    choose_device: 'Choose device',
    time_range: 'Time range',
    event_type: 'Event type',
    all_time: 'All time',
    today: 'Today',
    last_7_days: 'Last 7 days',
    this_month: 'This month',
    all: 'All',
    time: 'Time',
    actor: 'User / device',
    action_detail: 'Action details',
    try_again: 'Try again',
    no_matching_logs: 'No records match the current filter.',
    showing_filtered_results: 'Showing all results that match the filter.',
    login_title: 'Sign in',
    login_desc: 'Enter your account details to control devices safely.',
    login_submit: 'Secure sign in',
    register_title: 'Create account',
    register_desc: 'Create an account to use the system.',
    register_submit: 'Create account',
    remember_session: 'Keep me signed in',
    forgot_password: 'Forgot password?',
    no_account: 'Need access?',
    have_account: 'Already have an account?',
    sensor_temperature: 'Temperature',
    sensor_humidity: 'Humidity',
    sensor_gas: 'Gas',
    sensor_light: 'Light',
    sensor_motion: 'Motion',
    sensor_door_open: 'Door opened',
    sensor_door_close: 'Door closed',
    users: 'Users',
    global_sessions: 'Global sessions',
    full_name: 'Full name',
    role: 'Role',
    status: 'Status',
    last_login: 'Last login',
    actions: 'Actions',
    enable: 'Enable',
    disable: 'Disable',
    active: 'Active',
    disabled: 'Disabled',
    signed_in: 'Signed in',
    last_active: 'Last active',
    logged_out: 'Logged out',
  },
};

const polishedTranslations = {
  vn: {
    dashboard: 'Tổng quan',
    remote_control: 'Điều khiển',
    fingerprints: 'Vân tay',
    logs: 'Nhật ký',
    analytics: 'Phân tích',
    settings: 'Cài đặt',
    support: 'Hỗ trợ',
    support_page: 'Trang hỗ trợ',
    voice_control: 'Điều khiển giọng nói',
    voice_ready: 'Sẵn sàng',
    voice_listening: 'Đang nghe',
    voice_processing: 'Đang xử lý',
    voice_close: 'Đóng bảng giọng nói',
    voice_transcript: 'Nội dung nghe được',
    voice_speak_now: 'Hãy nói lệnh của bạn.',
    voice_no_transcript: 'Chưa có lệnh nào.',
    voice_examples: 'Lệnh mẫu',
    voice_history: 'Lịch sử lệnh',
    voice_panel: 'Giọng nói',
    voice_start: 'Bắt đầu nghe',
    voice_stop: 'Dừng nghe',
    voice_verify: 'Xác thực',
    voice_cancel: 'Hủy',
    logout: 'Đăng xuất',
    admin_sub: 'Quản trị viên',
    search: 'Tìm kiếm thiết bị...',
    sys_status: 'Trạng thái hệ thống',
    locked: 'Đã khóa',
    unlocked: 'Đã mở',
    sys_desc: 'Hệ thống an ninh Sentinel đang hoạt động. Tất cả điểm ra vào đều được bảo vệ.',
    wifi: 'Tín hiệu Wi-Fi',
    battery: 'Dung lượng pin',
    environment: 'Môi trường hiện tại',
    weather: 'Thời tiết',
    brightness: 'Ánh sáng',
    indoor: 'Trong nhà',
    gas: 'Khí gas',
    safe: 'An toàn',
    sensor_detail: 'Xem chi tiết cảm biến',
    alerts: 'Cảnh báo gần đây',
    view_all: 'Xem tất cả',
    live: 'Trực tiếp',
    front_door: 'Cửa chính',
    last_update: 'Cập nhật lần cuối',
    playback: 'Xem lại',
    talk: 'Đàm thoại',
    loading: 'Đang tải...',
    current_device: 'Thiết bị hiện tại',
    current_device_fallback: 'Chưa chọn thiết bị',
    online: 'Đang kết nối',
    offline: 'Mất kết nối',
    system_time: 'Thời gian hệ thống',
    switch_language: 'Chuyển ngôn ngữ',
    switch_theme: 'Chuyển giao diện',
    sentinel_user: 'Người dùng Sentinel',
    page_overview_title: 'Tổng quan hệ thống',
    page_overview_subtitle: 'Trạng thái cửa, cảnh báo và dữ liệu cần xử lý ngay.',
    page_remote_title: 'Điều khiển thiết bị',
    page_remote_subtitle: 'Gửi lệnh khóa mở và cập nhật cài đặt an toàn.',
    page_fingerprints_title: 'Quản lý vân tay',
    page_fingerprints_subtitle: 'Kiểm tra danh sách vân tay đang được cấp quyền.',
    page_logs_title: 'Nhật ký sự kiện',
    page_logs_subtitle: 'Theo dõi lịch sử ra vào, cảnh báo và thao tác hệ thống.',
    page_analytics_title: 'Phân tích hoạt động',
    page_analytics_subtitle: 'Tổng hợp xu hướng và mức độ ổn định của thiết bị.',
    page_settings_title: 'Tài khoản và tùy chọn',
    page_settings_subtitle: 'Cập nhật thông tin người dùng, thông báo và bảo mật.',
    profile_view: 'Xem hồ sơ',
    profile_view_desc: 'Xem thông tin tài khoản hiện tại',
    profile_edit: 'Sửa hồ sơ',
    profile_edit_desc: 'Cập nhật ảnh đại diện và thông tin cá nhân',
    preferences: 'Tùy chọn',
    preferences_desc: 'Giao diện và cài đặt tài khoản',
    login_activity: 'Hoạt động đăng nhập',
    login_activity_desc: 'Phiên đăng nhập và thiết bị gần đây',
    signing_out: 'Đang đăng xuất...',
    hero_attention: 'Cần xử lý ngay',
    hero_stable: 'Hệ thống ổn định',
    hero_needs_review: 'Hệ thống đang phát hiện sự kiện cần kiểm tra.',
    hero_device_online: 'đang kết nối bình thường.',
    hero_no_device_online: 'Chưa có thiết bị online. Kiểm tra kết nối trước khi điều khiển.',
    hero_scan: 'Tổng quan nhanh',
    door_status: 'Trạng thái cửa',
    active_alerts: 'Cảnh báo đang bật',
    device_label: 'Thiết bị',
    door_locked_now: 'Đã khóa',
    door_unlocked_now: 'Đang mở',
    unlock_now: 'Mở khóa ngay',
    lock_now: 'Khóa cửa ngay',
    view_alert_details: 'Xem chi tiết cảnh báo',
    view_weekly_report: 'Xem báo cáo tuần',
    next_action: 'Hành động tiếp theo',
    system_locked: 'Hệ thống đang khóa',
    relock_needed: 'Cần khóa lại cửa',
    next_action_online: 'Chuyển sang trang Điều khiển để xác thực và gửi lệnh khóa/mở.',
    next_action_offline: 'Thiết bị đang mất kết nối. Kiểm tra kết nối trước khi thao tác.',
    last_seen: 'Lần cập nhật cuối',
    latest_command: 'Lệnh gần nhất',
    ready: 'Sẵn sàng',
    active_alerts_title: 'Cảnh báo đang hoạt động',
    active_alerts_count_suffix: 'cảnh báo cần kiểm tra',
    no_active_alerts: 'Không có cảnh báo đang kích hoạt',
    view_logs: 'Xem nhật ký',
    loading_alerts: 'Đang tải cảnh báo...',
    system_safe: 'Hệ thống an toàn',
    system_safe_desc: 'Không có cảnh báo nào cần xử lý ở thời điểm hiện tại.',
    event_recent: 'Sự kiện gần đây',
    event_recent_desc: 'Trả lời nhanh: cửa đã khóa chưa, ai vừa thao tác, có sự cố nào mới không.',
    view_all_full: 'Xem toàn bộ',
    loading_events: 'Đang tải sự kiện...',
    no_events: 'Chưa có sự kiện nào trong nhật ký.',
    system_actor: 'Hệ thống',
    environment_desc: 'Giá trị hiện tại, đơn vị và mức cảnh báo cơ bản.',
    view_device: 'Xem thiết bị',
    weather_support: 'Dữ liệu bổ trợ hiện tại',
    ldr_sensor: 'Cảm biến ánh sáng',
    no_sensor_data: 'Chưa có dữ liệu từ cảm biến',
    threshold_label: 'Ngưỡng cảnh báo',
    too_bright: 'Quá sáng',
    stable: 'Ổn định',
    current_threshold: 'Ngưỡng hiện tại',
    needs_attention: 'Cần chú ý',
    motion_detected: 'Đang phát hiện chuyển động',
    no_intrusion: 'Không có xâm nhập',
    weekly_report: 'Báo cáo tuần',
    weekly_report_loading: 'Đang tổng hợp xu hướng 7 ngày qua.',
    weekly_report_fallback: 'Tổng hợp nhanh để xem hệ thống có ổn định hay không.',
    view_analytics: 'Xem phân tích',
    total_access: 'Lượt ra vào',
    new_alerts: 'Cảnh báo mới',
    critical_level: 'Mức nguy cấp',
    no_major_change: 'Không có thay đổi lớn',
    review_logs: 'Cần xem lại nhật ký và xử lý',
    no_new_alerts: 'Không có cảnh báo mới',
    prioritize_now: 'Cần ưu tiên xử lý',
    system_stable: 'Hệ thống vẫn ổn định',
    quick_insight: 'Nhận xét nhanh',
    insight_critical: 'Tuần này có cảnh báo nguy cấp. Ưu tiên vào trang Nhật ký để kiểm tra nguyên nhân và thời điểm xảy ra.',
    insight_warning: 'Có cảnh báo mới trong tuần nhưng chưa ở mức nguy cấp. Nên xem lại nhật ký để đảm bảo đã xử lý đầy đủ.',
    insight_ok: 'Hệ thống vẫn ổn định trong 7 ngày qua. Tiếp tục theo dõi kết nối thiết bị và nhật ký ra vào.',
    device_image: 'Hình ảnh thiết bị',
    device_preview: 'Xem trước thiết bị',
    device_preview_desc: 'Đây là khung xem trước thiết bị, không phải camera trực tiếp. Nếu cần xem trực tiếp, nên tách thành module camera riêng với trạng thái kết nối rõ ràng.',
    control_device: 'Điều khiển thiết bị',
    open_logs: 'Mở nhật ký',
    nav_scope_overview: 'Trạng thái tổng thể của hệ thống',
    nav_scope_remote: 'Thao tác khóa mở và cài đặt thiết bị',
    nav_scope_fingerprints: 'Quản lý danh tính và vân tay',
    nav_scope_logs: 'Theo dõi lịch sử và sự kiện',
    nav_scope_analytics: 'Báo cáo và xu hướng',
    nav_scope_settings: 'Tài khoản, bảo mật và thông báo',
    viewing: 'Đang xem',
    open_sidebar: 'Mở rộng thanh điều hướng',
    collapse_sidebar: 'Thu gọn thanh điều hướng',
    open_sidebar_short: 'Mở rộng',
    collapse_sidebar_short: 'Thu gọn',
    alert_critical: 'Nguy cấp',
    alert_high: 'Cần chú ý',
    alert_track: 'Theo dõi',
    alert_gas_leak: 'Cảnh báo khí gas',
    alert_intruder: 'Cảnh báo đột nhập',
    alert_fire: 'Cảnh báo cháy',
    alert_wrong_password: 'Sai mật khẩu',
    alert_tamper: 'Cảnh báo phá hoại',
    alert_battery_low: 'Pin yếu',
    alert_offline: 'Thiết bị mất kết nối',
    no_data: 'Chưa có dữ liệu',
    not_updated: 'Chưa cập nhật',
    fingerprints_total: 'Tổng số vân tay',
    fingerprints_active_today: 'Hoạt động trong ngày',
    fingerprints_security_level: 'Mức độ bảo mật',
    fingerprints_security_high: 'Cao',
    fingerprints_security_standard: 'Chuẩn',
    fingerprints_registry_title: 'Danh sách đăng ký',
    fingerprints_registry_desc: 'Quản lý và giám sát quyền truy cập sinh trắc học theo thời gian thực.',
    fingerprints_add_new: 'Thêm vân tay mới',
    fingerprints_table_slot: 'Vị trí lưu',
    fingerprints_table_user: 'Tên người dùng',
    fingerprints_table_access: 'Cấp độ truy cập',
    fingerprints_table_metadata: 'Thông tin đăng ký',
    fingerprints_table_last_active: 'Hoạt động lần cuối',
    fingerprints_table_actions: 'Thao tác',
    fingerprints_empty: 'Chưa có vân tay nào được đăng ký.',
    fingerprints_status_normal: 'Bình thường',
    fingerprints_status_disabled: 'Đã tắt',
    fingerprints_slot_label: 'Vị trí',
    fingerprints_active: 'Đang hoạt động',
    fingerprints_inactive: 'Tạm tắt',
    fingerprints_pagination_summary: 'Hiển thị 4 trong 128 kết quả',
    fingerprints_system_status: 'Trạng thái hệ thống',
    fingerprints_system_status_desc: 'Tất cả cảm biến vân tay đang hoạt động bình thường. Mã hóa đầu cuối đã được kích hoạt.',
    fingerprints_load_error: 'Không thể kết nối đến máy chủ.',
    fingerprints_level_standard: 'Tiêu chuẩn',
    fingerprints_level_admin: 'Quản trị',
    fingerprints_level_guest: 'Khách',
    fingerprints_enrollment_label: 'Đăng ký vân tay',
    fingerprints_add_modal_title: 'Thêm vân tay mới',
    fingerprints_add_modal_desc: 'Giao diện này mô phỏng quy trình thêm vân tay ở frontend. Khi backend sẵn sàng, phần gửi dữ liệu có thể nối trực tiếp vào API đăng ký mà không cần đổi bố cục.',
    fingerprints_close_modal: 'Đóng hộp thoại thêm vân tay',
    fingerprints_form_name: 'Tên người dùng',
    fingerprints_form_name_placeholder: 'Nhập tên người đăng ký',
    fingerprints_form_access: 'Cấp độ truy cập',
    fingerprints_form_slot: 'Vị trí đăng ký',
    fingerprints_form_slot_placeholder: 'Ví dụ: 12',
    fingerprints_form_note: 'Ghi chú nội bộ',
    fingerprints_form_note_placeholder: 'Mô tả thêm về người dùng, ngón tay đăng ký hoặc ghi chú vận hành.',
    fingerprints_sensor_status: 'Trạng thái cảm biến',
    fingerprints_sensor_ready: 'Sẵn sàng đăng ký',
    fingerprints_sensor_ready_desc: 'Thiết bị đang online và có thể bắt đầu nhận vân tay mới.',
    fingerprints_process_title: 'Quy trình đề xuất',
    fingerprints_process_desc: '1. Xác nhận thông tin người dùng. 2. Chọn vị trí lưu và khởi động đăng ký. 3. Yêu cầu đặt ngón tay 2-3 lần. 4. Lưu kết quả đăng ký khi thiết bị trả về thành công.',
    fingerprints_close: 'Đóng',
    fingerprints_start_enrollment: 'Bắt đầu đăng ký',
    fingerprints_preview: 'Xem trước',
    fingerprints_new_user: 'Người dùng mới',
    fingerprints_expected_slot: 'Vị trí dự kiến',
    fingerprints_not_selected: 'Chưa chọn',
    fingerprints_progress: 'Tiến trình',
    fingerprints_progress_desc: 'Bước 1/3: Nhập thông tin và sẵn sàng kết nối với thiết bị.',
    fingerprints_note_title: 'Lưu ý thao tác',
    fingerprints_note_desc: 'Người dùng nên đặt ngón tay sạch, khô và đúng vị trí trong mỗi lần quét để tăng độ chính xác.',
    reminder_warning: 'Cảnh báo',
    reminder_error: 'Lỗi hệ thống',
    reminder_info: 'Thông tin',
    reminder_success: 'Thành công',
    reminder_check_now: 'Kiểm tra ngay',
    reminder_close: 'Đóng',
    reminder_ok: 'Đồng ý',
    reminder_confirm: 'Xác nhận',
    reminder_cancel: 'Hủy',
    reminder_discard: 'Bỏ thay đổi',
    reminder_session_expired: 'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.',
    reminder_device_offline: 'Không thể kết nối tới thiết bị. Kiểm tra nguồn điện và mạng.',
    reminder_unsaved_changes: 'Bạn có thay đổi chưa lưu. Rời khỏi trang sẽ mất dữ liệu.',
    reminder_gas_detected: 'Hệ thống phát hiện nồng độ khí gas cao. Kiểm tra ngay!',
    reminder_intruder_detected: 'Phát hiện truy cập trái phép. Kiểm tra camera và nhật ký.',
    reminder_fire_detected: 'Phát hiện nguy cơ cháy. Kiểm tra ngay!',
    reminder_confirm_unlock: 'Bạn có chắc muốn mở khóa cửa?',
    reminder_confirm_lock: 'Bạn có chắc muốn khóa cửa?',
  },
};

const alertTypeKeys = {
  GAS_LEAK: 'alert_gas_leak',
  INTRUDER_ALERT: 'alert_intruder',
  FIRE_ALARM: 'alert_fire',
  WRONG_PASSWORD: 'alert_wrong_password',
  TAMPER_ALERT: 'alert_tamper',
  BATTERY_LOW: 'alert_battery_low',
  OFFLINE_ALERT: 'alert_offline',
};

const deviceNameMap = {
  vn: {
    'Front Door Lock': 'Khóa cửa chính',
    'Back Door Lock': 'Khóa cửa sau',
    'Main Door Lock': 'Khóa cửa chính',
  },
  en: {
    'Front Door Lock': 'Front door lock',
    'Back Door Lock': 'Back door lock',
    'Main Door Lock': 'Main door lock',
  },
};

const systemTextMap = {
  vn: {
    LOCKED: 'Đã khóa',
    UNLOCKED: 'Đã mở',
    REMOTE: 'Điều khiển từ xa',
    FINGERPRINT: 'Vân tay',
    SYSTEM: 'Hệ thống',
    'Dieu khien tu xa thanh cong qua Blynk V20': 'Điều khiển từ xa thành công qua Blynk V20',
    'Control command sent successfully via Blynk V20': 'Điều khiển từ xa thành công qua Blynk V20',
    'Voice control is ready.': 'Điều khiển giọng nói đã sẵn sàng.',
    'No command mapped yet': 'Chưa có lệnh nào.',
    'No voice command captured yet.': 'Chưa có lệnh nào.',
    'Speak a command now.': 'Hãy nói lệnh của bạn.',
    'Start listening and speak a short command.': 'Bấm bắt đầu nghe và nói một lệnh ngắn.',
    'The global engine parses and runs supported commands.': 'Hệ thống sẽ nhận diện và chạy lệnh được hỗ trợ.',
    'Lock and unlock run immediately; settings and alert resolution still verify identity.': 'Lệnh khóa/mở sẽ chạy ngay; cài đặt và xử lý cảnh báo vẫn cần xác thực.',
    'Use the floating mic to control the app from other pages.': 'Có thể dùng nút micro nổi để điều khiển từ các trang khác.',
    'Live browser security alerts': 'Cảnh báo bảo mật trực tiếp trên trình duyệt',
    'Daily and critical account summaries': 'Tổng hợp tài khoản hằng ngày và cảnh báo quan trọng',
    'Immediate gas leak notifications': 'Thông báo ngay khi phát hiện khí gas',
    'Unauthorized access activity': 'Hoạt động truy cập trái phép',
    'Failed keypad attempts': 'Các lần nhập sai mật khẩu',
    'Biometric enrollment and usage events': 'Sự kiện đăng ký và sử dụng vân tay',
    'Add a short bio to make your profile easier to recognize across security surfaces.': 'Thêm mô tả ngắn để dễ nhận diện hồ sơ trong hệ thống bảo mật.',
  },
  en: {
    LOCKED: 'Locked',
    UNLOCKED: 'Unlocked',
    REMOTE: 'Remote',
    FINGERPRINT: 'Fingerprint',
    SYSTEM: 'System',
    'Điều khiển từ xa thành công qua Blynk V20': 'Remote control completed successfully via Blynk V20',
    'Dieu khien tu xa thanh cong qua Blynk V20': 'Remote control completed successfully via Blynk V20',
  },
};

const LangContext = createContext();

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'vn');

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const toggleLang = () => {
    setLang((prev) => (prev === 'vn' ? 'en' : 'vn'));
  };

  const t = (key) => polishedTranslations[lang]?.[key] || translations[lang]?.[key] || phraseTranslations[lang]?.[key] || key;

  const locale = lang === 'vn' ? 'vi-VN' : 'en-US';

  const formatDateTime = (value, options = { dateStyle: 'short', timeStyle: 'short' }) => {
    if (!value) return t('unavailable');
    return new Date(value).toLocaleString(locale, options);
  };

  const formatRelativeTime = (value) => {
    if (!value) return t('not_updated');

    const diff = Date.now() - new Date(value).getTime();
    const minutes = Math.max(1, Math.round(diff / 60000));

    if (minutes < 60) return lang === 'vn' ? `${minutes} phút trước` : `${minutes} minute${minutes > 1 ? 's' : ''} ago`;
    const hours = Math.round(minutes / 60);
    if (hours < 24) return lang === 'vn' ? `${hours} giờ trước` : `${hours} hour${hours > 1 ? 's' : ''} ago`;
    const days = Math.round(hours / 24);
    return lang === 'vn' ? `${days} ngày trước` : `${days} day${days > 1 ? 's' : ''} ago`;
  };

  const formatAlertType = (alertType) => {
    const key = alertTypeKeys[String(alertType || '').toUpperCase()];
    return key ? t(key) : (alertType || t('system_notification'));
  };

  const formatAccessMethod = (method) => {
    const normalized = String(method || '').toUpperCase();
    const keys = {
      FINGERPRINT: 'fingerprint_method',
      REMOTE: 'remote_method',
      VOICE: 'voice_method',
      KEYPAD: 'keypad_method',
      SYSTEM: 'system_method',
      AUTO: 'system_method',
    };
    return t(keys[normalized] || 'system_method');
  };

  const formatAccessAction = (action) => {
    const normalized = String(action || '').toUpperCase();
    if (normalized === 'LOCKED') return t('locked_action');
    if (normalized === 'UNLOCKED') return t('unlocked_action');
    if (normalized === 'DENIED') return t('action_denied');
    if (normalized === 'TAMPERED' || normalized === 'ALARM') return t('action_warning');
    return action || t('unknown_info');
  };

  const formatDeviceName = (value) => {
    const name = String(value || '').trim();
    if (!name) return t('device_label');
    return deviceNameMap[lang]?.[name] || name;
  };

  const translateSystemText = (value) => {
    const text = String(value || '').trim();
    if (!text) return t('unknown_info');
    return systemTextMap[lang]?.[text] || text;
  };

  return (
    <LangContext.Provider value={{
      lang,
      locale,
      toggleLang,
      t,
      formatDateTime,
      formatRelativeTime,
      formatAlertType,
      formatAccessMethod,
      formatAccessAction,
      formatDeviceName,
      translateSystemText,
    }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);
