import React, { createContext, useContext, useEffect, useState } from 'react';

const translations = {
  vn: {
    dashboard: 'Tong quan',
    remote_control: 'Dieu khien',
    fingerprints: 'Van tay',
    logs: 'Nhat ky',
    analytics: 'Phan tich',
    settings: 'Cai dat',
    support: 'Ho tro',
    support_page: 'Trang ho tro',
    logout: 'Dang xuat',
    admin: 'Admin',
    admin_sub: 'Quan tri vien',
    search: 'Tim kiem thiet bi...',
    sys_status: 'Trang thai he thong',
    locked: 'DA KHOA',
    unlocked: 'DA MO',
    sys_desc: 'He thong an ninh Sentinel dang hoat dong. Tat ca diem truy cap deu duoc bao mat.',
    wifi: 'Tin hieu wifi',
    battery: 'Dung luong pin',
    environment: 'Moi truong hien tai',
    weather: 'Thoi tiet',
    brightness: 'Do sang (LDR)',
    indoor: 'Trong nha',
    gas: 'Nong do gas',
    safe: 'An toan',
    sensor_detail: 'Xem chi tiet cam bien',
    alerts: 'Canh bao gan day',
    view_all: 'Xem tat ca',
    live: 'TRUC TIEP',
    front_door: 'Cua chinh',
    last_update: 'Cap nhat lan cuoi',
    playback: 'Xem lai',
    talk: 'Dam thoai',
    loading: 'Dang tai...',
    current_device: 'Thiet bi hien tai',
    current_device_fallback: 'Chua chon thiet bi',
    online: 'Online',
    offline: 'Offline',
    system_time: 'Thoi gian he thong',
    switch_language: 'Chuyen ngon ngu',
    switch_theme: 'Chuyen giao dien',
    sentinel_user: 'Nguoi dung Sentinel',
    page_overview_title: 'Tong quan he thong',
    page_overview_subtitle: 'Trang thai cua, canh bao va du lieu can xu ly ngay.',
    page_remote_title: 'Dieu khien thiet bi',
    page_remote_subtitle: 'Gui lenh khoa mo va cap nhat cai dat an toan.',
    page_fingerprints_title: 'Quan ly van tay',
    page_fingerprints_subtitle: 'Kiem tra danh sach van tay dang duoc cap quyen.',
    page_logs_title: 'Nhat ky su kien',
    page_logs_subtitle: 'Theo doi lich su truy cap, canh bao va thao tac he thong.',
    page_analytics_title: 'Phan tich hoat dong',
    page_analytics_subtitle: 'Tong hop xu huong va muc do on dinh cua thiet bi.',
    page_settings_title: 'Tai khoan va tuy chon',
    page_settings_subtitle: 'Cap nhat thong tin nguoi dung, thong bao va bao mat.',
    profile_view: 'Xem ho so',
    profile_view_desc: 'Xem thong tin tai khoan hien tai',
    profile_edit: 'Sua ho so',
    profile_edit_desc: 'Cap nhat avatar va thong tin ca nhan',
    preferences: 'Tuy chon',
    preferences_desc: 'Giao dien va cai dat tai khoan',
    login_activity: 'Hoat dong dang nhap',
    login_activity_desc: 'Phien dang nhap va thiet bi gan day',
    signing_out: 'Dang dang xuat...',
    hero_attention: 'Can xu ly ngay',
    hero_stable: 'He thong on dinh',
    hero_needs_review: 'He thong dang phat hien su kien can kiem tra.',
    hero_device_online: 'dang ket noi binh thuong.',
    hero_no_device_online: 'Chua co thiet bi online. Kiem tra ket noi truoc khi dieu khien.',
    hero_scan: 'Tong quan 3 giay',
    door_status: 'Trang thai cua',
    active_alerts: 'Canh bao kich hoat',
    device_label: 'Thiet bi',
    door_locked_now: 'Da khoa',
    door_unlocked_now: 'Dang mo',
    unlock_now: 'Mo khoa ngay',
    lock_now: 'Khoa cua ngay',
    view_alert_details: 'Xem canh bao chi tiet',
    view_weekly_report: 'Xem bao cao tuan',
    next_action: 'Hanh dong tiep theo',
    system_locked: 'He thong dang khoa',
    relock_needed: 'Can khoa lai cua',
    next_action_online: 'Chuyen sang trang Dieu khien de xac thuc va gui lenh khoa/mo.',
    next_action_offline: 'Thiet bi dang offline. Kiem tra ket noi truoc khi thao tac.',
    last_seen: 'Lan cap nhat cuoi',
    latest_command: 'Lenh gan nhat',
    ready: 'San sang',
    active_alerts_title: 'Canh bao dang hoat dong',
    active_alerts_count_suffix: 'canh bao can kiem tra',
    no_active_alerts: 'Khong co canh bao dang kich hoat',
    view_logs: 'Xem nhat ky',
    loading_alerts: 'Dang tai canh bao...',
    system_safe: 'He thong an toan',
    system_safe_desc: 'Khong co canh bao nao can xu ly o thoi diem hien tai.',
    event_recent: 'Su kien gan day',
    event_recent_desc: 'Tra loi nhanh: cua da khoa chua, ai vua thao tac, co su co nao moi khong.',
    view_all_full: 'Xem toan bo',
    loading_events: 'Dang tai su kien...',
    no_events: 'Chua co su kien nao trong nhat ky.',
    system_actor: 'He thong',
    environment_desc: 'Gia tri hien tai, don vi va muc canh bao co ban.',
    view_device: 'Xem thiet bi',
    weather_support: 'Du lieu bo tro hien tai',
    ldr_sensor: 'Cam bien LDR',
    no_sensor_data: 'Chua co du lieu tu cam bien',
    threshold_label: 'Nguong canh bao',
    too_bright: 'Qua sang',
    stable: 'On dinh',
    current_threshold: 'Nguong hien tai',
    needs_attention: 'Can chu y',
    motion_detected: 'Dang phat hien chuyen dong',
    no_intrusion: 'Khong co xam nhap',
    weekly_report: 'Bao cao tuan',
    weekly_report_loading: 'Dang tong hop xu huong 7 ngay qua.',
    weekly_report_fallback: 'Tong hop nhanh de xem he thong co on dinh hay khong.',
    view_analytics: 'Xem phan tich',
    total_access: 'Luot truy cap',
    new_alerts: 'Canh bao moi',
    critical_level: 'Muc nguy cap',
    no_major_change: 'Khong co thay doi lon',
    review_logs: 'Can xem lai nhat ky va xu ly',
    no_new_alerts: 'Khong co canh bao moi',
    prioritize_now: 'Can uu tien xu ly',
    system_stable: 'He thong van on dinh',
    quick_insight: 'Insight nhanh',
    insight_critical: 'Tuan nay co canh bao nguy cap. Uu tien vao trang Nhat ky de kiem tra nguyen nhan va thoi diem xay ra.',
    insight_warning: 'Co canh bao moi trong tuan nhung chua o muc nguy cap. Nen xem lai nhat ky de dam bao da xu ly day du.',
    insight_ok: 'He thong van on dinh trong 7 ngay qua. Tiep tuc theo doi ket noi thiet bi va log truy cap.',
    device_image: 'Hinh anh thiet bi',
    device_preview: 'Preview thiet bi',
    device_preview_desc: 'Day la khung preview thiet bi, khong phai live camera. Neu can goc nhin truc tiep, nen tach thanh module camera rieng voi trang thai ket noi ro rang.',
    control_device: 'Dieu khien thiet bi',
    open_logs: 'Mo nhat ky',
    nav_scope_overview: 'Trang thai tong the cua he thong',
    nav_scope_remote: 'Thao tac khoa mo va cai dat thiet bi',
    nav_scope_fingerprints: 'Quan ly danh tinh va van tay',
    nav_scope_logs: 'Theo doi lich su va su kien',
    nav_scope_analytics: 'Bao cao va xu huong',
    nav_scope_settings: 'Tai khoan, bao mat va thong bao',
    viewing: 'Dang xem',
    open_sidebar: 'Mo rong thanh dieu huong',
    collapse_sidebar: 'Thu gon thanh dieu huong',
    open_sidebar_short: 'Mo rong sidebar',
    collapse_sidebar_short: 'Thu gon sidebar',
    alert_critical: 'Nguy cap',
    alert_high: 'Can chu y',
    alert_track: 'Theo doi',
    alert_gas_leak: 'Canh bao khi gas',
    alert_intruder: 'Canh bao dot nhap',
    alert_fire: 'Canh bao chay',
    alert_wrong_password: 'Sai mat khau',
    alert_tamper: 'Canh bao pha hoai',
    alert_battery_low: 'Pin yeu',
    alert_offline: 'Thiet bi offline',
    no_data: 'Chua co du lieu',
    not_updated: 'Chua cap nhat',
    minutes_ago: 'phut truoc',
    hours_ago: 'gio truoc',
    days_ago: 'ngay truoc',
    fingerprints_total: 'Tong so van tay',
    fingerprints_active_today: 'Hoat dong trong ngay',
    fingerprints_security_level: 'Muc do bao mat',
    fingerprints_security_high: 'Cao',
    fingerprints_security_standard: 'Chuan',
    fingerprints_registry_title: 'Danh sach dang ky',
    fingerprints_registry_desc: 'Quan ly va giam sat quyen truy cap sinh trac hoc theo thoi gian thuc.',
    fingerprints_add_new: 'Them van tay moi',
    fingerprints_table_slot: 'Slot ID',
    fingerprints_table_user: 'Ten nguoi dung',
    fingerprints_table_access: 'Cap do truy cap',
    fingerprints_table_metadata: 'Metadata dang ky',
    fingerprints_table_last_active: 'Hoat dong lan cuoi',
    fingerprints_table_actions: 'Thao tac',
    fingerprints_empty: 'Chua co van tay nao duoc dang ky.',
    fingerprints_status_normal: 'Binh thuong',
    fingerprints_status_disabled: 'Vo hieu hoa',
    fingerprints_slot_label: 'Slot',
    fingerprints_active: 'Active',
    fingerprints_inactive: 'Inactive',
    fingerprints_pagination_summary: 'Hien thi 4 trong so 128 ket qua',
    fingerprints_system_status: 'Trang thai he thong',
    fingerprints_system_status_desc: 'Tat ca cam bien van tay dang hoat dong binh thuong. Ma hoa dau cuoi da duoc kich hoat.',
    fingerprints_load_error: 'Khong the ket noi den may chu.',
    fingerprints_level_standard: 'Standard',
    fingerprints_level_admin: 'Admin',
    fingerprints_level_guest: 'Guest',
    fingerprints_enrollment_label: 'Dang ky van tay',
    fingerprints_add_modal_title: 'Them van tay moi',
    fingerprints_add_modal_desc: 'Giao dien nay mo phong quy trinh them van tay o frontend. Khi backend san sang, phan submit co the noi truc tiep vao API enrollment ma khong can doi layout.',
    fingerprints_close_modal: 'Dong hop thoai them van tay',
    fingerprints_form_name: 'Ten nguoi dung',
    fingerprints_form_name_placeholder: 'Nhap ten nguoi dang ky',
    fingerprints_form_access: 'Cap do truy cap',
    fingerprints_form_slot: 'Slot dang ky',
    fingerprints_form_slot_placeholder: 'Vi du: 12',
    fingerprints_form_note: 'Ghi chu noi bo',
    fingerprints_form_note_placeholder: 'Mo ta them ve nguoi dung, ngon tay dang ky, hoac ghi chu van hanh.',
    fingerprints_sensor_status: 'Trang thai cam bien',
    fingerprints_sensor_ready: 'San sang enrollment',
    fingerprints_sensor_ready_desc: 'Thiet bi dang online va co the bat dau nhan van tay moi.',
    fingerprints_process_title: 'Quy trinh de xuat',
    fingerprints_process_desc: '1. Xac nhan thong tin nguoi dung. 2. Chon slot va khoi dong enrollment. 3. Yeu cau dat ngon tay 2-3 lan. 4. Luu ket qua dang ky khi thiet bi tra ve thanh cong.',
    fingerprints_close: 'Dong',
    fingerprints_start_enrollment: 'Bat dau dang ky',
    fingerprints_preview: 'Preview',
    fingerprints_new_user: 'Nguoi dung moi',
    fingerprints_expected_slot: 'Slot du kien',
    fingerprints_not_selected: 'Chua chon',
    fingerprints_progress: 'Tien trinh',
    fingerprints_progress_desc: 'Buoc 1/3: Nhap thong tin va san sang ket noi voi thiet bi.',
    fingerprints_note_title: 'Luu y thao tac',
    fingerprints_note_desc: 'Nguoi dung nen dat ngon tay sach, kho va dung vi tri trong moi lan quet de tang do chinh xac.',
  },
  en: {
    dashboard: 'Overview',
    remote_control: 'Control',
    fingerprints: 'Fingerprints',
    logs: 'Logs',
    analytics: 'Analytics',
    settings: 'Settings',
    support: 'Support',
    support_page: 'Support Page',
    logout: 'Log out',
    admin: 'Admin',
    admin_sub: 'Administrator',
    search: 'Search devices...',
    sys_status: 'System status',
    locked: 'LOCKED',
    unlocked: 'UNLOCKED',
    sys_desc: 'Sentinel security system is active. All access points are secured.',
    wifi: 'Wi-Fi signal',
    battery: 'Battery level',
    environment: 'Current environment',
    weather: 'Weather',
    brightness: 'Brightness (LDR)',
    indoor: 'Indoor',
    gas: 'Gas level',
    safe: 'Safe',
    sensor_detail: 'View sensor details',
    alerts: 'Recent alerts',
    view_all: 'View all',
    live: 'LIVE',
    front_door: 'Front door',
    last_update: 'Last updated',
    playback: 'Playback',
    talk: 'Talk',
    loading: 'Loading...',
    current_device: 'Current device',
    current_device_fallback: 'No device selected',
    online: 'Online',
    offline: 'Offline',
    system_time: 'System time',
    switch_language: 'Switch language',
    switch_theme: 'Switch theme',
    sentinel_user: 'Sentinel User',
    page_overview_title: 'System overview',
    page_overview_subtitle: 'Door status, active alerts, and data that needs action now.',
    page_remote_title: 'Device control',
    page_remote_subtitle: 'Send lock commands and update safety settings.',
    page_fingerprints_title: 'Fingerprint management',
    page_fingerprints_subtitle: 'Review fingerprints that currently have access.',
    page_logs_title: 'Event log',
    page_logs_subtitle: 'Track access history, alerts, and system actions.',
    page_analytics_title: 'Activity analytics',
    page_analytics_subtitle: 'Review trends and overall device stability.',
    page_settings_title: 'Account and preferences',
    page_settings_subtitle: 'Update profile, notifications, and security options.',
    profile_view: 'View profile',
    profile_view_desc: 'Review your current account details',
    profile_edit: 'Edit profile',
    profile_edit_desc: 'Update avatar and personal information',
    preferences: 'Settings',
    preferences_desc: 'Appearance and account preferences',
    login_activity: 'Login activity',
    login_activity_desc: 'Recent sessions and devices',
    signing_out: 'Signing out...',
    hero_attention: 'Needs attention now',
    hero_stable: 'System stable',
    hero_needs_review: 'The system has detected an event that should be reviewed.',
    hero_device_online: 'is connected and operating normally.',
    hero_no_device_online: 'No online devices found. Check connectivity before sending commands.',
    hero_scan: 'Three-second summary',
    door_status: 'Door status',
    active_alerts: 'Active alerts',
    device_label: 'Device',
    door_locked_now: 'Locked',
    door_unlocked_now: 'Unlocked',
    unlock_now: 'Unlock now',
    lock_now: 'Lock now',
    view_alert_details: 'View alert details',
    view_weekly_report: 'View weekly report',
    next_action: 'Next action',
    system_locked: 'System is locked',
    relock_needed: 'Door should be locked again',
    next_action_online: 'Go to the Control page to verify identity and send a lock or unlock command.',
    next_action_offline: 'The device is offline. Check connectivity before taking action.',
    last_seen: 'Last seen',
    latest_command: 'Latest command',
    ready: 'Ready',
    active_alerts_title: 'Active alerts',
    active_alerts_count_suffix: 'alerts need review',
    no_active_alerts: 'No active alerts',
    view_logs: 'View logs',
    loading_alerts: 'Loading alerts...',
    system_safe: 'System secure',
    system_safe_desc: 'There are no alerts that require action right now.',
    event_recent: 'Recent events',
    event_recent_desc: 'Answer quickly: is the door locked, who acted last, and is there any new issue?',
    view_all_full: 'View all',
    loading_events: 'Loading events...',
    no_events: 'No events in the log yet.',
    system_actor: 'System',
    environment_desc: 'Current values, units, and basic warning thresholds.',
    view_device: 'View device',
    weather_support: 'Current supporting data',
    ldr_sensor: 'LDR sensor',
    no_sensor_data: 'No sensor data available',
    threshold_label: 'Warning threshold',
    too_bright: 'Too bright',
    stable: 'Stable',
    current_threshold: 'Current threshold',
    needs_attention: 'Needs attention',
    motion_detected: 'Motion currently detected',
    no_intrusion: 'No intrusion detected',
    weekly_report: 'Weekly report',
    weekly_report_loading: 'Compiling the last 7 days of activity...',
    weekly_report_fallback: 'A quick summary to check whether the system stayed stable.',
    view_analytics: 'View analytics',
    total_access: 'Access count',
    new_alerts: 'New alerts',
    critical_level: 'Critical level',
    no_major_change: 'No major change',
    review_logs: 'Review logs and resolve if needed',
    no_new_alerts: 'No new alerts',
    prioritize_now: 'Prioritize now',
    system_stable: 'System remained stable',
    quick_insight: 'Quick insight',
    insight_critical: 'There were critical alerts this week. Go to Logs first to review cause and timing.',
    insight_warning: 'There were new alerts this week, but not at a critical level. Review the log to confirm everything was handled.',
    insight_ok: 'The system stayed stable over the last 7 days. Keep monitoring device connectivity and access activity.',
    device_image: 'Device image',
    device_preview: 'Device preview',
    device_preview_desc: 'This is a device preview, not a live camera feed. If you need live video, it should be a dedicated module with clear connection state.',
    control_device: 'Control device',
    open_logs: 'Open logs',
    nav_scope_overview: 'Overall system state',
    nav_scope_remote: 'Lock, unlock, and configure device settings',
    nav_scope_fingerprints: 'Identity and fingerprint management',
    nav_scope_logs: 'History and event tracking',
    nav_scope_analytics: 'Reports and trends',
    nav_scope_settings: 'Account, security, and notification settings',
    viewing: 'Viewing',
    open_sidebar: 'Expand navigation',
    collapse_sidebar: 'Collapse navigation',
    open_sidebar_short: 'Expand sidebar',
    collapse_sidebar_short: 'Collapse sidebar',
    alert_critical: 'Critical',
    alert_high: 'Needs review',
    alert_track: 'Tracking',
    alert_gas_leak: 'Gas leak alert',
    alert_intruder: 'Intruder alert',
    alert_fire: 'Fire alarm',
    alert_wrong_password: 'Wrong password',
    alert_tamper: 'Tamper alert',
    alert_battery_low: 'Low battery',
    alert_offline: 'Device offline',
    no_data: 'No data available',
    not_updated: 'Not updated yet',
    minutes_ago: 'minutes ago',
    hours_ago: 'hours ago',
    days_ago: 'days ago',
    fingerprints_total: 'Total fingerprints',
    fingerprints_active_today: 'Activity today',
    fingerprints_security_level: 'Security level',
    fingerprints_security_high: 'High',
    fingerprints_security_standard: 'Standard',
    fingerprints_registry_title: 'Enrollment list',
    fingerprints_registry_desc: 'Manage and monitor biometric access permissions in real time.',
    fingerprints_add_new: 'Add new fingerprint',
    fingerprints_table_slot: 'Slot ID',
    fingerprints_table_user: 'User name',
    fingerprints_table_access: 'Access level',
    fingerprints_table_metadata: 'Enrollment metadata',
    fingerprints_table_last_active: 'Last activity',
    fingerprints_table_actions: 'Actions',
    fingerprints_empty: 'No fingerprints have been registered yet.',
    fingerprints_status_normal: 'Normal',
    fingerprints_status_disabled: 'Disabled',
    fingerprints_slot_label: 'Slot',
    fingerprints_active: 'Active',
    fingerprints_inactive: 'Inactive',
    fingerprints_pagination_summary: 'Showing 4 of 128 results',
    fingerprints_system_status: 'System status',
    fingerprints_system_status_desc: 'All fingerprint sensors are operating normally. End-to-end encryption is active.',
    fingerprints_load_error: 'Unable to connect to the server.',
    fingerprints_level_standard: 'Standard',
    fingerprints_level_admin: 'Admin',
    fingerprints_level_guest: 'Guest',
    fingerprints_enrollment_label: 'Fingerprint enrollment',
    fingerprints_add_modal_title: 'Add new fingerprint',
    fingerprints_add_modal_desc: 'This frontend flow simulates fingerprint enrollment. When the backend is ready, submission can connect directly to the enrollment API without changing the layout.',
    fingerprints_close_modal: 'Close add fingerprint dialog',
    fingerprints_form_name: 'User name',
    fingerprints_form_name_placeholder: 'Enter the enrollee name',
    fingerprints_form_access: 'Access level',
    fingerprints_form_slot: 'Enrollment slot',
    fingerprints_form_slot_placeholder: 'Example: 12',
    fingerprints_form_note: 'Internal note',
    fingerprints_form_note_placeholder: 'Describe the user, selected finger, or any operational note.',
    fingerprints_sensor_status: 'Sensor status',
    fingerprints_sensor_ready: 'Ready for enrollment',
    fingerprints_sensor_ready_desc: 'The device is online and ready to capture a new fingerprint.',
    fingerprints_process_title: 'Recommended flow',
    fingerprints_process_desc: '1. Confirm user information. 2. Pick a slot and start enrollment. 3. Ask the user to place the finger 2 to 3 times. 4. Save the result when the device reports success.',
    fingerprints_close: 'Close',
    fingerprints_start_enrollment: 'Start enrollment',
    fingerprints_preview: 'Preview',
    fingerprints_new_user: 'New user',
    fingerprints_expected_slot: 'Expected slot',
    fingerprints_not_selected: 'Not selected',
    fingerprints_progress: 'Progress',
    fingerprints_progress_desc: 'Step 1/3: Enter details and prepare device connection.',
    fingerprints_note_title: 'Handling note',
    fingerprints_note_desc: 'The user should keep the finger clean, dry, and aligned consistently during each scan for better accuracy.',
  },
};

const LangContext = createContext();

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'vn');

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const toggleLang = () => {
    setLang((prev) => (prev === 'vn' ? 'en' : 'vn'));
  };

  const t = (key) => translations[lang]?.[key] || key;

  return <LangContext.Provider value={{ lang, toggleLang, t }}>{children}</LangContext.Provider>;
};

export const useLang = () => useContext(LangContext);
