UPDATE user_devices
SET permission = CASE UPPER(permission)
    WHEN 'READ' THEN 'VIEW_ONLY'
    WHEN 'VIEW_ONLY' THEN 'VIEW_ONLY'
    WHEN 'WRITE' THEN 'CONTROL'
    WHEN 'EXECUTE' THEN 'CONTROL'
    WHEN 'CONTROL' THEN 'CONTROL'
    WHEN 'ADMIN' THEN 'OWNER'
    WHEN 'OWNER' THEN 'OWNER'
    ELSE permission
END;
